export const stringsData = {
  screens: {
    cowList: {
      title: 'Cow Management',
      searchPlaceholder: 'Search by ear tag...',
      filterByStatus: 'Filter by Status',
      filterByPen: 'Filter by Pen',
      addCowButton: 'Add New Cow',
      noCowsFound: 'No cows found',
      noCowsMessage: 'Add your first cow to get started',
      earTag: 'Ear Tag',
      sex: 'Sex',
      pen: 'Pen',
      status: 'Status',
      lastEvent: 'Last Event',
      allStatuses: 'All Statuses',
      allPens: 'All Pens',
      clearFilters: 'Clear Filters',
      clearDataTitle: 'Clear All Data',
      clearDataMessage: 'Are you sure you want to delete all cow data? This action cannot be undone.',
      clearDataConfirm: 'Clear All',
      clearDataSuccess: 'All data cleared successfully',
    },
    addCow: {
      title: 'Add New Cow',
      subtitle: 'Fill in the required information to add a new cow to your herd.',
      editTitle: 'Edit Cow',
      earTagLabel: 'Ear Tag *',
      earTagPlaceholder: 'Enter ear tag number',
      sexLabel: 'Sex *',
      selectSex: 'Select sex',
      male: 'Male',
      female: 'Female',
      penLabel: 'Pen *',
      penPlaceholder: 'Enter pen number',
      statusLabel: 'Status *',
      selectStatus: 'Select status',
      active: 'Active',
      inTreatment: 'In Treatment',
      deceased: 'Deceased',
      weightLabel: 'Weight (kg)',
      weightPlaceholder: 'Enter weight',
      saveButton: 'Save Cow',
      cancelButton: 'Cancel',
      errorEarTagRequired: 'Ear tag is required',
      errorEarTagExists: 'Ear tag already exists',
      errorSexRequired: 'Sex is required',
      errorPenRequired: 'Pen is required',
      errorStatusRequired: 'Status is required',
      errorWeightInvalid: 'Weight must be a positive number',
      successMessage: 'Cow saved successfully',
    },
    cowDetail: {
      title: 'Cow Details',
      basicInfo: 'Basic Information',
      earTag: 'Ear Tag',
      sex: 'Sex',
      pen: 'Pen',
      status: 'Status',
      currentWeight: 'Current Weight',
      dailyWeightGain: 'Daily Weight Gain',
      createdDate: 'Created Date',
      timeline: 'Event Timeline',
      noEvents: 'No events recorded yet',
      eventTypes: {
        Created: 'Created',
        'Weight Check': 'Weight Check',
        Treatment: 'Treatment',
        'Pen Change': 'Pen Changed',
        'Status Change': 'Status Changed',
        Death: 'Death',
      },
      kg: 'kg',
      kgPerDay: 'kg/day',
      notAvailable: 'N/A',
    },
  },
  common: {
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    confirm: 'Confirm',
    ok: 'OK',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    required: 'Required',
    optional: 'Optional',
  },
} as const;

